name: CI-TEST
on:
  workflow_dispatch:
    inputs:
      epo:
        type: string
        description: "repo name"
        required: true
jobs:
  new:
    name: "Provision New"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Create new team repo
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.MANAGE_REPOS_TOKEN }}
        run: |
          REPO_EXISTS_ID=$(curl -L \
            -X GET \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ steps.account_request.outputs.new_infra_live_repo_name }} | jq .id)
          echo $REPO_EXISTS_ID
          if [ REPO_EXISTS_ID != null ]; then
            echo "REPO EXISTS"
          else
            echo "NULL"
          fi
          
