name: CI-TEST
on:
  workflow_dispatch:
    inputs:
      repo_name:
        type: string
        description: "repo name"
        required: true
jobs:
  new:
    name: "Provision New"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Create new team repo
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.MANAGE_REPOS_TOKEN }}
        run: |
          REPO_EXISTS_ID=$(curl -L \
            -X GET \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ inputs.repo_name }} | jq .id)

          if [ $REPO_EXISTS_ID == null ]; then
            gh api \
              --method POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /orgs/${{ github.repository_owner }}/repos \
              -f name=${{ inputs.repo_name }} \
              -f visibility=private \
              -f auto_init=true
          fi
          
