name: CI-TEST
on:
  workflow_dispatch:
    inputs:
      repo_name:
        type: string
        description: "repo name"
        required: true
jobs:
  new:
    name: "Provision New"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v3.6.0
      - name: Create new team repo
        id: create_new_team_repo
        env:
          GH_TOKEN: ${{ secrets.MANAGE_REPOS_TOKEN }}
          GH_ORG: ${{ github.repository_owner }}
          GH_NEW_INFRA_LIVE_REPO_NAME: "new-repo-1"
        run: |
          # Check if the repo exists before trying to create it
          GH_REPO_STATUS_CODE="$(curl --silent --write-out '%{http_code}' --output /dev/null \
            -X GET \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$GH_ORG/$GH_NEW_INFRA_LIVE_REPO_NAME")"

          # If the repo does not exist (404 status code), then create it
          if [[ "$GH_REPO_STATUS_CODE" == 404 ]]; then
            gh api \
              --method POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /orgs/$GH_ORG/repos \
              -f name=$GH_NEW_INFRA_LIVE_REPO_NAME \
              -f visibility=public \
              -f auto_init=true

              echo "::notice title=New team repo created!::See created repository: https://github.com/$GH_ORG/$GH_NEW_INFRA_LIVE_REPO_NAME."

          # If the repo exists (200 status code), print a message and continue
          elif [[ "$GH_REPO_STATUS_CODE" == 200 ]]; then
            echo "Repository https://github.com/$GH_ORG/$GH_NEW_INFRA_LIVE_REPO_NAME already exists."

          # If GH returns a non 200 or non 404 status code, print and exit with an error
          else
            echo "Status code $GH_REPO_STATUS_CODE returned from GitHub API. Exiting with error."
            exit 1
          fi

      - name: Set new repo branch protection
        id: set_branch_protection
        env:
          GH_TOKEN: ${{ secrets.MANAGE_REPOS_TOKEN }}
          GH_ORG: ${{ github.repository_owner }}
          GH_NEW_INFRA_LIVE_REPO_NAME: "new-repo-1"
        run: |
          echo "Setting branch protection rules for $GH_ORG/$GH_NEW_INFRA_LIVE_REPO_NAME. See https://docs.gruntwork.io/pipelines/security/branch-protection for more information on recommended rules."
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$GH_ORG/$GH_NEW_INFRA_LIVE_REPO_NAME/branches/main/protection \
            -d '{ "required_status_checks": { "strict": true, "checks": [ ] }, "required_pull_request_reviews": { "require_code_owner_reviews": true, "require_last_push_approval": true, "required_approving_review_count": 1 }, "enforce_admins": false, "restrictions": null }'
