name: CI-TEST
on:
  workflow_dispatch:
    inputs:
      epo:
        type: string
        description: "repo name"
        required: true
jobs:
  new:
    name: "Provision New"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Create new team repo
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.MANAGE_REPOS_TOKEN }}
        run: |
          REPO_EXISTS_ID=$(gh api \
            --method GET \
            -H "Accept: application/vnd.github.v3+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository_owner }}/${{ steps.account_request.outputs.new_infra_live_repo_name }} | jq .id)
          if [ REPO_EXISTS_ID != "null" ]; then
            echo "REPO EXISTS"
          else
            echo "NULL"
          fi
          
